### ISSUE TITLE
steven: go panics on run

### ISSUE THREAD

**Issue by spotlightishere** [Thinkofname/steven-go#73]
I have an iMac running El Capitan (10.11.4). I installed `go` using Homebrew.

When I run `steven`, I'm getting this panic:

```
panic: reflect: reflect.Value.Set using value obtained using unexported field

goroutine 1 [running]:
panic(0x451af20, 0xc8202a2140)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
reflect.flag.mustBeAssignable(0x1d9)
    /usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:226 +0x161
reflect.Value.Set(0x46f3880, 0xc8200517a0, 0x1d9, 0x46f3880, 0xc820051650, 0x1d9)
    /usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:1328 +0x25
github.com/thinkofdeath/steven.cloneBlock(0x56c7d40, 0xc820051650, 0x0, 0x0)
    /Users/joshua/Projects/Minecraft/go/build/src/github.com/thinkofdeath/steven/block.go:407 +0x282
github.com/thinkofdeath/steven.alloc(0x56c7d40, 0xc820051650, 0xc820051650)
    /Users/joshua/Projects/Minecraft/go/build/src/github.com/thinkofdeath/steven/block.go:389 +0x9ca
github.com/thinkofdeath/steven.init.5()
    /Users/joshua/Projects/Minecraft/go/build/src/github.com/thinkofdeath/steven/blocks.go:277 +0x6b2
github.com/thinkofdeath/steven.init()
    /Users/joshua/Projects/Minecraft/go/build/src/github.com/thinkofdeath/steven/world.go:23 +0x55ed
main.init()
    /Users/joshua/Projects/Minecraft/go/build/src/github.com/thinkofdeath/steven/cmd/steven/steven.go:    62 +0x4a
```

I do not have a `steven-log.txt` as it never generated/existed.

**Comment by 0x277F** [comment]
https://gyazo.com/1602b19a4f800ac00cb396d951ad9020

**Comment by spotlightishere** [comment]
I know it is not actively maintained anymore. I figured I would open this to see if anyone in the community knew how to fix it.

**Comment by Thinkofname** [comment]
I think either go 1.5 or 1.6 broke it due to me (unknowingly) relying on a bug.

**Comment by spotlightishere** [comment]
Can confirm, downgrading to go 1.4 made it run as expected.
